### ISSUE TITLE
[error：rqt_calibrator]，

### ISSUE THREAD

**Issue by Averykla** [marcoesposito1988/easy_handeye2#8]
Hello dear author, I got an error when executing calibrate.launch.py ​​of easy_handeye2. The error message is: [ERROR] [rqt_calibrator.py-3]: process has died [pid 44838, exit code 1, cmd '/home/cookies/ros2_Vi/install/easy_handeye2/lib/easy_handeye2/rqt_calibrator.py --ros-args -r __node:=handeye_rqt_calibrator --params-file /tmp/launch_params_bmah6r2e']. 
How should I solve this problem?I would be very grateful if you could help me with this problem！

**Comment by cemoke** [comment]
We have the same error. Any help would be appreciated

**Comment by santoshbalaji** [comment]
I have faced similar issues as well when the aruco marker is not in field of view of the camera. You can try using this following pull request. It has all these issues resolved.

[https://github.com/marcoesposito1988/easy_handeye2/pull/7](https://github.com/marcoesposito1988/easy_handeye2/pull/7)

**Comment by cemoke** [comment]
> I have faced similar issues as well when the aruco marker is not in field of view of the camera. You can try using this following pull request. It has all these issues resolved.
> 
> #7

Yes, this PR solves the issues. Thanks!

**Comment by ycheng517** [comment]
the aforementioned PR has been merged btw, so this issue can be closed
